version: '2.2'

services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'mikeknox/gcr']
    volumes:
      - ".:/plugin"

  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin"

  shellcheck:
    image: koalaman/shellcheck:latest
    command: hooks/pre-command 
    working_dir: /plugin
    volumes:
      - ".:/plugin"