name: GCR
description: "Login to GCR in your build steps."
author: "@mikeknox"
public: true
requirements:
  - curl
  - bash
  - gcp
configuration:
  properties:
    login:
      type: boolean
  required:
    - login
  additionalProperties: false