#!/bin/bash

set -eu -o pipefail

# Reads either a value or a list from plugin config
function plugin_read_list() {
  local prefix="BUILDKITE_PLUGIN_GCR_$1"
  local parameter="${prefix}_0"

  if [[ -n "${!parameter:-}" ]]; then
    local i=0
    local parameter="${prefix}_${i}"
    while [[ -n "${!parameter:-}" ]]; do
      echo "${!parameter}"
      i=$((i+1))
      parameter="${prefix}_${i}"
    done
  elif [[ -n "${!prefix:-}" ]]; then
    echo "${!prefix}"
  fi
}

# For logging into the GCR registry
if [[ "${BUILDKITE_PLUGIN_GCR_LOGIN:-}" =~ ^(true|1)$ ]] ; then

  echo "~~~ Authenticating with GCP GCR"

  gcr_login=$(docker login -u _json_key -p "$( printf "%s" "${BUILDKITE_PLUGIN_GCR_JSON_KEY:-}" )" https://gcr.io) || exit $?

  echo "$gcr_login"
fi
